name: jaffle_dbt
version: "1.0.0"
config-version: 2

profile: jaffle_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  jaffle_dbt:
    strict: false
